---
components:
  schemas:
    AirQualitySensor:
      $ref: "https://raw.githubusercontent.com/kkotenidis/SensorsTUC/main/AirQualitySensor.yaml#/AirQuality"
info:
  description: "AirQuality Sensor by Kydon for T, RH, CO2, NO2, O3, PM10, PM25, SO2, windSpeed, windDirection"
title: AirQuality Sensor by Kydon
  version: "0.0.1"
openapi: "3.0.0"

paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        ? "200"
        :
          content:
            application/ld+json:
              schema:
                type: object
          description: OK
