---
components:
  schemas:
    IoTSensor:
      $ref: "https://raw.githubusercontent.com/kkotenidis/SensorsTUC/main/IoTSensor.yaml#/IotSensor"
info:
  description: "IoT Sensor by Kydon for T, RH, soilMoisture"
  title: IoT Sensor by Kydon
  version: "0.0.1"
openapi: "3.0.0"

paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        ? "200"
        :
          content:
            application/ld+json:
              schema:
                type: object
          description: OK
